import { Record } from './types';

export const initialRecords: Record[] = [
  {
    id: '1',
    storeName: '南门阿姨灌饼',
    budget: '10↓',
    scene: '独行',
    noise: '沸腾',
    speed: '极快',
    details: ['排队王', '碳水炸弹', '早八救星'],
    photoUrl: 'https://images.unsplash.com/photo-1555126634-323283e090fa?auto=format&fit=crop&w=800&q=80',
    soulNote: '刚出炉的灌饼刷上秘制甜面酱，夹上一根淀粉肠，是早八人最后的救赎。',
    author: '早八特种兵',
    campus: '仙林校区',
    stamps: 342,
    createdAt: Date.now() - 100000,
  },
  {
    id: '2',
    storeName: '二食堂糖水铺',
    budget: '10↓',
    scene: '双人',
    noise: '正常',
    speed: '极快',
    details: ['夏日续命', '料超足', '阿姨手不抖'],
    photoUrl: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=800&q=80',
    soulNote: '五块钱一碗的绿豆沙牛乳，绵密起沙，甜度克制，抚平了整个夏天的燥热。',
    author: '甜品脑袋',
    campus: '鼓楼校区',
    stamps: 285,
    createdAt: Date.now() - 200000,
  },
  {
    id: '3',
    storeName: '老柳州螺蛳粉',
    budget: '15-30',
    scene: '独行',
    noise: '沸腾',
    speed: '正常',
    details: ['重口味', '加炸蛋', '无限续粉'],
    photoUrl: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=800&q=80',
    soulNote: '红油盖顶，酸笋的独特气味直冲天灵盖。吸满汤汁的炸蛋，是这碗粉里绝对的灵魂。',
    author: '嗦粉狂魔',
    campus: '仙林校区',
    stamps: 410,
    createdAt: Date.now() - 300000,
  },
  {
    id: '4',
    storeName: '隆江猪脚饭',
    budget: '15-30',
    scene: '团建',
    noise: '正常',
    speed: '极快',
    details: ['男大快乐饭', '肥而不腻', '无限加饭'],
    photoUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
    soulNote: '卤得软烂入味的猪脚，满满的胶原蛋白拌着米饭，每一口都是碳水与脂肪的狂欢。',
    author: '干饭王',
    campus: '鼓楼校区',
    stamps: 188,
    createdAt: Date.now() - 400000,
  },
  {
    id: '5',
    storeName: '萨瓦迪卡小馆',
    budget: '50-80',
    scene: '聚餐',
    noise: '沸腾',
    speed: '正常',
    details: ['冬阴功', '平价泰餐', '氛围感'],
    photoUrl: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?auto=format&fit=crop&w=800&q=80',
    soulNote: '冬阴功汤酸辣开胃，香茅与青柠的气息交织。人均六十的正宗泰北风味，期末聚餐首选。',
    author: '寻味客',
    campus: '仙林校区',
    stamps: 156,
    createdAt: Date.now() - 500000,
  },
  {
    id: '6',
    storeName: '深夜食堂·鸟烧',
    budget: '50-80',
    scene: '双人',
    noise: '微醺',
    speed: '极慢',
    details: ['烧鸟', '梅子酒', '深夜emo'],
    photoUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80',
    soulNote: '炭火烤制的京葱鸡腿肉外焦里嫩，配上一杯微甜的梅酒，足以慰藉赶完论文的疲惫夜晚。',
    author: '夜游神',
    campus: '鼓楼校区',
    stamps: 234,
    createdAt: Date.now() - 600000,
  },
  {
    id: '7',
    storeName: 'Aether Brunch',
    budget: '50-80',
    scene: '约会',
    noise: '低语',
    speed: '正常',
    details: ['全日早午餐', '出片圣地', '插座友好'],
    photoUrl: 'https://images.unsplash.com/photo-1513442542250-854d436a73f2?auto=format&fit=crop&w=800&q=80',
    soulNote: '水波蛋切开的瞬间，流心的蛋黄与牛油果泥完美融合。这里的拿铁有着迷人的坚果香气。',
    author: '半日闲',
    campus: '仙林校区',
    stamps: 142,
    createdAt: Date.now() - 700000,
  },
  {
    id: '8',
    storeName: '牛阵·寿喜锅',
    budget: '100-150',
    scene: '团建',
    noise: '沸腾',
    speed: '正常',
    details: ['和牛畅吃', '无菌蛋', '扶墙出'],
    photoUrl: 'https://images.unsplash.com/photo-1526413232644-8a40f4110b46?auto=format&fit=crop&w=800&q=80',
    soulNote: '裹满无菌蛋液的牛肉入口顺滑鲜甜。这是拿到奖学金后，犒劳整个宿舍的最佳选择。',
    author: '肉食动物',
    campus: '仙林校区',
    stamps: 375,
    createdAt: Date.now() - 800000,
  },
  {
    id: '9',
    storeName: 'Osteria 1998',
    budget: '100-150',
    scene: '约会',
    noise: '低语',
    speed: '极慢',
    details: ['手工意面', '氛围拉满', '暗调微醺'],
    photoUrl: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=800&q=80',
    soulNote: '黑松露蘑菇烩饭浓郁得化不开，每一粒米都吸饱了汤汁。适合在这个昏暗的角落里，谈论理想与爱。',
    author: '罗马假日',
    campus: '鼓楼校区',
    stamps: 110,
    createdAt: Date.now() - 900000,
  },
  {
    id: '10',
    storeName: '焰·炭火烧肉',
    budget: '150-200',
    scene: '庆生',
    noise: '沸腾',
    speed: '正常',
    details: ['厚切牛舌', '全程帮烤', '生日惊喜'],
    photoUrl: 'https://images.unsplash.com/photo-1544025162-8a1152645800?auto=format&fit=crop&w=800&q=80',
    soulNote: '厚切牛舌在烤网上滋滋作响，剪开后透着诱人的粉色。这是学生时代能触及的，最顶级的肉食狂欢。',
    author: '风雅颂',
    campus: '仙林校区',
    stamps: 230,
    createdAt: Date.now() - 1000000,
  }
];
